[package]
name = "cpuid"
version = "0.0.0"
authors = ["Steven Noonan <steven@uplinklabs.net>"]

[profile.release]
opt-level = "s"
lto = "thin"
codegen-units = 1

[dependencies]
clap = "^2"
num_cpus = "^1"
affinity = "^0"
