name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [stable, beta, nightly, macos, win32, win64, mingw]
        include:
          - build: stable
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-gnu
          - build: beta
            os: ubuntu-latest
            rust: beta
            target: x86_64-unknown-linux-gnu
          - build: nightly
            os: ubuntu-latest
            rust: nightly
            target: x86_64-unknown-linux-gnu
          - build: macos
            os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
          - build: win32
            os: windows-latest
            rust: stable
            target: i686-pc-windows-msvc
          - build: win64
            os: windows-latest
            rust: stable
            target: x86_64-pc-windows-msvc
          - build: mingw
            os: windows-latest
            rust: stable
            target: x86_64-pc-windows-gnu
    steps:
    - uses: actions/checkout@master
    - name: Install Rust (rustup)
      run: |
        rustup target add ${{ matrix.target }}
        rustup update ${{ matrix.rust }} --no-self-update
        rustup default ${{ matrix.rust }}
    - name: Test (no default features)
      run: |
        cargo test --no-fail-fast --tests --verbose --no-default-features ${{ matrix.target }}
    - name: Test (legacy TLBs)
      run: |
        cargo test --no-fail-fast --tests --verbose --no-default-features --features="legacy-tlb-descriptors,build-binaries" ${{ matrix.target }}
    - name: Test (default features)
      run: |
        cargo test --no-fail-fast --tests --verbose --target ${{ matrix.target }}
    - name: Run (dump)
      run: |
        cargo run --target ${{ matrix.target }} --bin cpuid-dump
      env:
        RUST_LOG: debug
    - name: Run (decode)
      run: |
        cargo run --target ${{ matrix.target }} --bin cpuid-decode
      env:
        RUST_LOG: debug

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: |
        rustup update nightly --no-self-update
        rustup default nightly
        rustup component add rustfmt
    - name: Run rustfmt
      run: |
        cargo fmt -- --check
